### PR TITLE
Update README.md after following the instructions

### PR DESCRIPTION
**Pull request by henrikrxn**
On SDK 7.0.100 and tried to follow the instructions in the README.md

When installing the template per step 1.

1. Install the template - `dotnet new -i CarterTemplate`

This is purely FYI, I am not changing anything to address the warning I got:

 ❯  dotnet new -i CarterTemplate
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead. For more information, run:
   dotnet new install -h

The following template packages will be installed:
   CarterTemplate

Success: CarterTemplate::7.0.0 installed the following templates:
Template Name    Short Name  Language  Tags
---------------  ----------  --------  ------------------------------
Carter Template  carter      [C#]      Carter/Carter Template/NancyFX

For step 2:

2. Create a new application using template - `dotnet new Carter -n MyCarterApp`

I got this error:

 ❯  dotnet new Carter -n MyCarterApp
No templates or subcommands found matching: 'Carter'. Did you mean one of the following templates?
   dotnet new carter

To list installed templates similar to 'Carter', run:
   dotnet new list Carter
To search for the templates on NuGet.org, run:
   dotnet new search Carter

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

I then did as suggested and ran:

 ❯  dotnet new carter -n MyCarterApp

which created files directly in the current directory, so I added a step to create a new folder and go into that. I would suggest creating a new .sln file considering you use the phrase "application" several times, but I can see how that might be problematic for people wanting to try Carter on existing projects.

### CODE REVIEW

**Comment by jchannon** [comment]
Thanks for the PR! Your points are valid and correct but all we need to do
is change the readme with this

dotnet new Carter -n MyCarterApp -o MyCarterApp

This will create the directory and put the project in it. If you want to
change your PR to do that I’ll happily merge it.

Also your sln idea to add to the template is a good idea so we could change
the template too

**Comment by henrikrxn** [comment]
Did the update you suggested which I might have thought about if I use the command line more.

Leaving adding the .sln for another PR, but will create issue for it, that I might (no promises) pick up.

**Comment by henrikrxn** [comment]
NB: I think you still need to lowercase the C in `dotnet new Carter` so I kept that.

**Review by jchannon — APPROVED** [review]

**Comment by jchannon** [comment]
Thanks 👍

**Pull request merged**
