### PR TITLE
Solution to support Enum's in OpenAPI for Issue #262

### PR DESCRIPTION
**Pull request by Dreamwalker666**
Created a possible solution for issue #262

### CODE REVIEW

**Comment by JoeStead** [comment]
I wonder if there should be some config option for this. Enums in C# are a bit weird imo, it makes sense (mostly) for them to be serialised as strings, but I have come across solutions using integers over the wire (this is a bad idea, but we should cater for it)

**Review by JoeStead — APPROVED** [review]
That said, the implementation of this seems pretty sound

**Comment by Dreamwalker666** [comment]
> I wonder if there should be some config option for this. Enums in C# are a bit weird imo, it makes sense (mostly) for them to be serialised as strings, but I have come across solutions using integers over the wire (this is a bad idea, but we should cater for it)

I honestly have the same thoughts but decided to first implement in the way OpenAPI expects.  I really think its a bad idea to use numbers! (pesky magic numbers)

Maybe use a custom attribute to override the behavior?  I think strings should be the default (we should encourage good API design) but allow it to expose the numeric values.  I guess as well turn off (but currently it gives out a blank object which isn't useful at all)

**Comment by JoeStead** [comment]
Ooof, would be wary of magic attributes. I think string defaults make sense, perhaps an extension to the CarterOptions to allow an override? I thinking turning it off makes no sense, so either string (default) or number (override)

**Comment by Dreamwalker666** [comment]
> Ooof, would be wary of magic attributes. I think string defaults make sense, perhaps an extension to the CarterOptions to allow an override? I thinking turning it off makes no sense, so either string (default) or number (override)

I only said attribute as you may have some enums that require number but not all.  Also the number they will still have to be a string in the schema as enum only supports string from what I've read.

**Review by jchannon — APPROVED** [review]

**Comment by jchannon** [comment]
Can you do a rebase please before I merge!?

**Comment by Dreamwalker666** [comment]
@jchannon ok sorted it was expecting that issue due to the other branch :)

**Comment by jchannon** [comment]
Nice! Thanks 👍

**Pull request merged**
