### PR TITLE
Fix exception with form binding and nullable types

### LINKED ISSUE #198: Invalid cast from 'System.String' to 'System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
Fails to bind a string to bool. Blows up with the error:

Invalid cast from 'System.String' to 'System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.

image

### PR DESCRIPTION
**Pull request by welshdave**
Fixes #198

### CODE REVIEW

**Comment by jchannon** [comment]
Looking good. Will take a proper look tomorrow. Thanks!

**Comment by jchannon** [comment]
This is up to you but I see a few comments here about some TypeConverters not working in certain circumstances and would like to expand the tests a bit to ensure that we can convert those. If you want to take a look let me know or I'll merge then take a look and fix any issues if they exist https://www.hanselman.com/blog/TypeConvertersTheresNotEnoughTypeDescripterGetConverterInTheWorld.aspx

**Comment by welshdave** [comment]
Wouldn't be able to look for a few days (travelling in to office to prove I still exist), but could look Thursday or Friday?

**Comment by jchannon** [comment]
Cool!

**Comment by welshdave** [comment]
So TypeConverters have a few problems - don't think it's worth using them. I've updated and added a few more tests.

**Comment by jchannon** [comment]
What was the issues with them?

**Comment by welshdave** [comment]
They lose precision when converting datetime (loses milliseconds), seem to be a lot more picky about date formatting than other conversion methods. 

And for number formatting, strings like "1,234.00" don't convert (try converting that to a decimal, it fails with the TypeConverter approach, works fine with Convert.ChangeType).

**Comment by jchannon** [comment]
Is it worth adding some tests for decimals?

**Comment by welshdave** [comment]
Yeah, I'll add some now

**Comment by jchannon** [comment]
Thanks @welshdave Awesome stuff!

**Pull request merged**
