### PR TITLE
Readme - Getting Started update

### LINKED ISSUE #114: Readme.md doesn't say how to install just the package
The readme file has instructions for installing the template, but not the package on its own.

### PR DESCRIPTION
**Pull request by j0nnyhughes**
Updated the readme to close #114

### CODE REVIEW

**Comment by jchannon** [comment]
Awesome stuff! Thanks a lot! 👍

**Comment by j0nnyhughes** [comment]
Sorry, just noticed the numbering in the package section.  Whats the best way to fix it?

**Comment by jchannon** [comment]
Well spotted, I missed it too! Feel free to send another PR if you want to fix it :)

**Comment by j0nnyhughes** [comment]
yep i'll do that soon

**Pull request merged**
