### PR TITLE
Bind logging

### PR DESCRIPTION
**Pull request by jeffdoolittle**
@jchannon is this along the lines of what you had in mind? Also, I can revert the .sln and global.json changes if you prefer. Let me know.

### CODE REVIEW

**Comment by JoeStead** [comment]
Hey Jeff, thanks for the PR, it's appreciated!

I haven't looked at it in detail right now, but I have noticed a couple of styling inconsistencies, using `_myVar` instead of `this.myVar` for example. 

I know there's no style guide as such, but consistency with other code would be great!

**Comment by jeffdoolittle** [comment]
Fixed the naming to match, and reverted the .sln and global.json changes.

**Comment by jeffdoolittle** [comment]
Did a bit more clean up:

* put `using` statements inside namespaces to match the rest of the codebase
* added test coverage to validate the logging behavior for the model binding

**Comment by jchannon** [comment]
Awesome stuff! Thanks @jeffdoolittle 👍

**Pull request merged**
